version: '3.5'

services:
  go_db:
    container_name: 'go_db'
    ports:
      - '5432:5433' 
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin

    image: postgres:14.3-alpine